import type {
  PaletteFamily,
  PlanetArchetype,
  PlanetAtmosphereFamily,
  PlanetEffect,
  PlanetHydrologyFamily,
  PlanetReliefFamily,
  PlanetShapeFamily,
  PlanetSizeCategory,
  PlanetSurfaceFamily,
  PlanetTerrainFamily,
} from './planet-visual.types';

export interface ArchetypeIdentityRule {
  weight: number;
  allowedSizeCategories: PlanetSizeCategory[];
  allowedShapeFamilies: PlanetShapeFamily[];
  allowedReliefFamilies: PlanetReliefFamily[];
  allowedHydrologyFamilies: PlanetHydrologyFamily[];
  allowedSurfaceFamilies: PlanetSurfaceFamily[];
  allowedPaletteFamilies: PaletteFamily[];
  allowedAtmosphereFamilies: PlanetAtmosphereFamily[];
  allowedTerrainProfiles: PlanetTerrainFamily[];
  allowedEffects: PlanetEffect[];
  forbiddenEffects: PlanetEffect[];
  targetLandRatio: { min: number; max: number };
  targetOceanRatio: { min: number; max: number };
  elevationCapRange: { min: number; max: number };
  rareTraits?: string[];
}

export const MIN_GAMEPLAY_LAND_RATIO = 0.4;
export const MIN_VISUAL_LAND_RATIO = 0.46;

export const ARCHETYPE_IDENTITY_RULES: Record<PlanetArchetype, ArchetypeIdentityRule> = {
  oceanic: {
    weight: 1.1,
    allowedSizeCategories: ['medium', 'large'],
    allowedShapeFamilies: ['stable-spheroid', 'eroded'],
    allowedReliefFamilies: ['gentle', 'moderate'],
    allowedHydrologyFamilies: ['waterworld', 'balanced'],
    allowedSurfaceFamilies: ['ocean', 'lush'],
    allowedPaletteFamilies: ['emerald-sea', 'cobalt-ice', 'verdant-umber'],
    allowedAtmosphereFamilies: ['standard', 'dense'],
    allowedTerrainProfiles: ['smooth', 'moderate', 'continental'],
    allowedEffects: ['banding', 'icecaps', 'aurora'],
    forbiddenEffects: ['thermal'],
    targetLandRatio: { min: 0.46, max: 0.62 },
    targetOceanRatio: { min: 0.44, max: 0.66 },
    elevationCapRange: { min: 0.18, max: 0.25 },
  },
  lush: {
    weight: 0.9,
    allowedSizeCategories: ['medium', 'large'],
    allowedShapeFamilies: ['stable-spheroid', 'eroded', 'tectonic'],
    allowedReliefFamilies: ['moderate', 'rugged'],
    allowedHydrologyFamilies: ['balanced'],
    allowedSurfaceFamilies: ['lush', 'ocean'],
    allowedPaletteFamilies: ['verdant-umber', 'emerald-sea', 'basalt-moss'],
    allowedAtmosphereFamilies: ['standard', 'dense'],
    allowedTerrainProfiles: ['continental', 'moderate', 'rough'],
    allowedEffects: ['banding', 'icecaps', 'aurora'],
    forbiddenEffects: ['thermal'],
    targetLandRatio: { min: 0.48, max: 0.7 },
    targetOceanRatio: { min: 0.3, max: 0.52 },
    elevationCapRange: { min: 0.2, max: 0.29 },
  },
  arid: {
    weight: 1,
    allowedSizeCategories: ['small', 'medium', 'large'],
    allowedShapeFamilies: ['eroded', 'tectonic'],
    allowedReliefFamilies: ['moderate', 'rugged'],
    allowedHydrologyFamilies: ['arid', 'dry'],
    allowedSurfaceFamilies: ['desert', 'barren'],
    allowedPaletteFamilies: ['arid-ochre', 'ember-dust', 'sulfur-stone'],
    allowedAtmosphereFamilies: ['none', 'thin', 'standard'],
    allowedTerrainProfiles: ['rough', 'moderate'],
    allowedEffects: ['craters', 'banding'],
    forbiddenEffects: ['aurora'],
    targetLandRatio: { min: 0.62, max: 0.86 },
    targetOceanRatio: { min: 0.06, max: 0.28 },
    elevationCapRange: { min: 0.22, max: 0.33 },
  },
  icy: {
    weight: 0.95,
    allowedSizeCategories: ['small', 'medium', 'large'],
    allowedShapeFamilies: ['stable-spheroid', 'eroded'],
    allowedReliefFamilies: ['gentle', 'moderate'],
    allowedHydrologyFamilies: ['cryo', 'balanced'],
    allowedSurfaceFamilies: ['ice', 'ocean'],
    allowedPaletteFamilies: ['cobalt-ice', 'glacier-mint', 'rose-quartz'],
    allowedAtmosphereFamilies: ['thin', 'standard', 'dense'],
    allowedTerrainProfiles: ['smooth', 'moderate'],
    allowedEffects: ['icecaps', 'banding', 'aurora'],
    forbiddenEffects: ['thermal'],
    targetLandRatio: { min: 0.44, max: 0.66 },
    targetOceanRatio: { min: 0.2, max: 0.46 },
    elevationCapRange: { min: 0.18, max: 0.27 },
  },
  volcanic: {
    weight: 0.62,
    allowedSizeCategories: ['small', 'medium'],
    allowedShapeFamilies: ['tectonic', 'fragmented-shell'],
    allowedReliefFamilies: ['rugged', 'extreme'],
    allowedHydrologyFamilies: ['dry'],
    allowedSurfaceFamilies: ['volcanic', 'barren'],
    allowedPaletteFamilies: ['obsidian-lava', 'ember-dust', 'charcoal-abyss'],
    allowedAtmosphereFamilies: ['none', 'thin', 'reactive'],
    allowedTerrainProfiles: ['extreme', 'rough', 'fragmented'],
    allowedEffects: ['thermal', 'craters', 'banding'],
    forbiddenEffects: ['aurora'],
    targetLandRatio: { min: 0.72, max: 0.92 },
    targetOceanRatio: { min: 0, max: 0.12 },
    elevationCapRange: { min: 0.26, max: 0.38 },
    rareTraits: ['lava-seas'],
  },
  dead: {
    weight: 0.64,
    allowedSizeCategories: ['small', 'medium', 'large'],
    allowedShapeFamilies: ['eroded', 'tectonic'],
    allowedReliefFamilies: ['moderate', 'rugged'],
    allowedHydrologyFamilies: ['dry', 'arid'],
    allowedSurfaceFamilies: ['barren', 'mineral'],
    allowedPaletteFamilies: ['charcoal-abyss', 'sulfur-stone', 'basalt-moss'],
    allowedAtmosphereFamilies: ['none', 'thin'],
    allowedTerrainProfiles: ['rough', 'moderate'],
    allowedEffects: ['craters'],
    forbiddenEffects: ['aurora', 'thermal'],
    targetLandRatio: { min: 0.66, max: 0.9 },
    targetOceanRatio: { min: 0, max: 0.18 },
    elevationCapRange: { min: 0.21, max: 0.3 },
  },
  toxic: {
    weight: 0.56,
    allowedSizeCategories: ['medium', 'large'],
    allowedShapeFamilies: ['tectonic', 'fragmented-shell'],
    allowedReliefFamilies: ['rugged', 'extreme'],
    allowedHydrologyFamilies: ['arid', 'balanced'],
    allowedSurfaceFamilies: ['toxic', 'abyssal'],
    allowedPaletteFamilies: ['toxic-neon', 'amethyst-haze', 'violet-ash'],
    allowedAtmosphereFamilies: ['reactive', 'dense'],
    allowedTerrainProfiles: ['extreme', 'rough'],
    allowedEffects: ['thermal', 'banding', 'craters'],
    forbiddenEffects: [],
    targetLandRatio: { min: 0.52, max: 0.76 },
    targetOceanRatio: { min: 0.12, max: 0.36 },
    elevationCapRange: { min: 0.23, max: 0.34 },
  },
  mineral: {
    weight: 0.84,
    allowedSizeCategories: ['small', 'medium', 'large'],
    allowedShapeFamilies: ['tectonic', 'eroded'],
    allowedReliefFamilies: ['rugged', 'moderate'],
    allowedHydrologyFamilies: ['arid', 'dry'],
    allowedSurfaceFamilies: ['mineral', 'barren'],
    allowedPaletteFamilies: ['sulfur-stone', 'charcoal-abyss', 'rose-quartz'],
    allowedAtmosphereFamilies: ['none', 'thin', 'standard'],
    allowedTerrainProfiles: ['rough', 'moderate', 'fragmented'],
    allowedEffects: ['craters', 'banding'],
    forbiddenEffects: ['aurora'],
    targetLandRatio: { min: 0.62, max: 0.86 },
    targetOceanRatio: { min: 0.02, max: 0.24 },
    elevationCapRange: { min: 0.22, max: 0.34 },
  },
  clouded: {
    weight: 0.56,
    allowedSizeCategories: ['medium', 'large'],
    allowedShapeFamilies: ['stable-spheroid', 'eroded'],
    allowedReliefFamilies: ['gentle', 'moderate'],
    allowedHydrologyFamilies: ['balanced', 'cryo'],
    allowedSurfaceFamilies: ['ice', 'ocean', 'abyssal'],
    allowedPaletteFamilies: ['glacier-mint', 'rose-quartz', 'cobalt-ice'],
    allowedAtmosphereFamilies: ['dense', 'reactive'],
    allowedTerrainProfiles: ['smooth', 'moderate'],
    allowedEffects: ['banding', 'aurora', 'icecaps'],
    forbiddenEffects: ['thermal'],
    targetLandRatio: { min: 0.46, max: 0.66 },
    targetOceanRatio: { min: 0.24, max: 0.52 },
    elevationCapRange: { min: 0.18, max: 0.27 },
  },
  exotic: {
    weight: 0.5,
    allowedSizeCategories: ['small', 'medium', 'large'],
    allowedShapeFamilies: ['tectonic', 'fragmented-shell', 'eroded'],
    allowedReliefFamilies: ['moderate', 'rugged', 'extreme'],
    allowedHydrologyFamilies: ['balanced', 'arid', 'cryo'],
    allowedSurfaceFamilies: ['toxic', 'abyssal', 'mineral'],
    allowedPaletteFamilies: ['amethyst-haze', 'violet-ash', 'rose-quartz'],
    allowedAtmosphereFamilies: ['reactive', 'dense', 'standard'],
    allowedTerrainProfiles: ['extreme', 'rough', 'fragmented', 'moderate'],
    allowedEffects: ['thermal', 'banding', 'aurora', 'craters'],
    forbiddenEffects: [],
    targetLandRatio: { min: 0.46, max: 0.78 },
    targetOceanRatio: { min: 0.08, max: 0.38 },
    elevationCapRange: { min: 0.2, max: 0.36 },
    rareTraits: ['chromatic-shift'],
  },
  fragmented: {
    weight: 0.58,
    allowedSizeCategories: ['small', 'medium'],
    allowedShapeFamilies: ['fragmented-shell', 'tectonic'],
    allowedReliefFamilies: ['fragmented', 'rugged', 'extreme'],
    allowedHydrologyFamilies: ['arid', 'balanced'],
    allowedSurfaceFamilies: ['barren', 'desert', 'mineral'],
    allowedPaletteFamilies: ['ember-dust', 'arid-ochre', 'charcoal-abyss'],
    allowedAtmosphereFamilies: ['none', 'thin', 'standard'],
    allowedTerrainProfiles: ['fragmented', 'rough', 'extreme'],
    allowedEffects: ['craters', 'banding'],
    forbiddenEffects: ['aurora'],
    targetLandRatio: { min: 0.64, max: 0.9 },
    targetOceanRatio: { min: 0, max: 0.18 },
    elevationCapRange: { min: 0.24, max: 0.36 },
  },
  superterran: {
    weight: 0.22,
    allowedSizeCategories: ['large'],
    allowedShapeFamilies: ['stable-spheroid', 'tectonic'],
    allowedReliefFamilies: ['moderate', 'rugged'],
    allowedHydrologyFamilies: ['balanced'],
    allowedSurfaceFamilies: ['lush', 'ocean', 'mineral'],
    allowedPaletteFamilies: ['verdant-umber', 'emerald-sea', 'basalt-moss', 'cobalt-ice'],
    allowedAtmosphereFamilies: ['standard', 'dense'],
    allowedTerrainProfiles: ['continental', 'rough', 'moderate'],
    allowedEffects: ['banding', 'icecaps', 'aurora'],
    forbiddenEffects: ['thermal'],
    targetLandRatio: { min: 0.58, max: 0.78 },
    targetOceanRatio: { min: 0.16, max: 0.34 },
    elevationCapRange: { min: 0.2, max: 0.3 },
    rareTraits: ['mega-basins'],
  },
};
